# ReplicaSet ScaleOut Example

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-rs
spec:
  replicas: 4
  selector:    # selector: label기반으로 다른 오브젝트를 식별하고 제어한다.
    matchLabels: # 체크할 Label. 하위 key-value가 모두 같아야 한다. 
      app: echo
      tier: app
  template:
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: ghcr.io/subicura/echo:v1