# 레플리카셋(복제셋) 예시
# ReplicaSet은 "지정된 수"의 "동일한 Pod들"이 "항상 실행"되도록 한다.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-rs
spec:
  replicas: 1  # Pod 개수
  selector:    # selector: label기반으로 다른 오브젝트를 식별하고 제어한다.
    matchLabels: # 체크할 Label. 하위 key-value가 모두 같아야 한다. 
      app: echo
      tier: app
  template:    # 생성할 Pod 명세
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: ghcr.io/subicura/echo:v1