# redis (db server) pod을 deploy한다
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-metadata-redis
spec:
  selector:    # selector: label기반으로 다른 오브젝트를 식별하고 제어한다.
    matchLabels:
      app: sampleapp
      tier: db
  template:    # template: pod의 구성 및 메타데이터
    metadata:
      labels:
        app: sampleapp
        tier: db
    spec:
      containers:
        - name: container-redisdb
          image: redis
          ports:
            - containerPort: 6379
              protocol: TCP
