# Service 예제 - ClusterIP
# 다른 Pod(app-access-to-redis.yml)를 실행시켜 여기서 정의한 Service에 접근해보자 (service-metadata-redis:3333)
apiVersion: v1
kind: Service
metadata:
  name: service-metadata-redis
spec:
  # type: ClusterIP # (default)
  ports:
    - protocol: TCP
      port: 3333       # service에서 open할 port
      targetPort: 6379 # 대상 Pod(container)에 open된 port # default: 위 port와 동일
  selector:
    app: sampleapp
    tier: db
---
# redis (db server) pod을 deploy한다
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-metadata-redis
spec:
  selector:    # selector: label기반으로 다른 오브젝트를 식별하고 제어한다.
    matchLabels:
      app: sampleapp
      tier: db
  template:    # template: pod의 구성 및 메타데이터
    metadata:
      labels:
        app: sampleapp
        tier: db
    spec:
      containers:
        - name: container-redisdb
          image: redis
          ports:
            - containerPort: 6379
              protocol: TCP
