# Service 예제 - LoadBalancer
# 대상 Pod(0_deploy_server-client-example.yml)를 미리 켜두고, 
# 클러스터 외부에서 브라우저 또는 curl로 {nodeIP}:{nodePort}에 접근해보자
# minikube의 경우 단일 Node이므로,
  # minikube ip 로 출력되는 ip가 nodeIP에 해당한다.
  # minikube + docker driver 조합의 경우 minikube service {service_name}을 이용하자.
apiVersion: v1
kind: Service
metadata:
  name: svc-loadbalancer
spec:
  type: LoadBalancer
  # 포트 정보
  # LoadBalancer 타입에서 nodePort는 자동생성된다.
  ports:
    - protocol: TCP
      port: 3333       # Service에서 open할 port
      targetPort: 6379 # 대상 Pod(container)에 open된 port  # default: 위 port와 동일
      
  # Service에 연동될 대상 Pod 지정 (0_deploy_server-client-example.yml)
  selector:
    app: sampleapp
    tier: db
