# Service 예제 - LoadBalancer

# 실행 후 ExternalIP와 nodePort는 LB타입 Service 실행시 자동할당되는 것으로 kubectl get svc 에서 확인가능
  # nodePort가 랜덤배정된 것을 확인해보자.
  # External IP는 클라우드 미사용시 로드밸런서가 없어서 할당되지 않고 pending이라고 표기됨
  # 따라서 접속불가 상태

  # MetalLB라는 서드파티 가상 로드밸런서로 클라우드없이 LB타입 Service 배포가능
    # 이를 이용해 로컬에서도 LB타입을 테스트해볼 수 있다.
    # (metallb-for-minikube.yml) 참고!!
    # MetalLB에서 External IP 미할당 이슈가 있는데, 버전or K8s배포판마다 문제원인이 너무 다양해서 별도 설정필요
    

apiVersion: v1
kind: Service
metadata:
  name: svc-loadbalancer
spec:
  type: LoadBalancer
  # 포트 정보
  # LoadBalancer 타입에서 nodePort는 자동생성된다.
  ports:
    - protocol: TCP
      port: 3333       # Service에서 open할 port
      targetPort: 6379 # 대상 Pod(container)에 open된 port  # default: 위 port와 동일
  
  #####################################################
  # 어떤 Service에 대해 로드밸런싱할 때 node단위로 할지 Pod 단위로 할지 설정
    # Cluster(default) =>해당 Service 소속 모든 Pod에 traffic이 균등 분포된다. 더블홉딜레마 발생
    # Local => 단일 Node 내 해당 Service소속 Pod에서만 traffic이 분산된다.
  #####################################################
  #externalTrafficPolicy: Local


  #####################################################
  # LoadBalancerIP
  # 원래, LoadBalancer(LB) IP는 사용가능한 IP범위 중 자동할당되는데,
  # 이 옵션을 쓰면, 해당 범위 중 원하는 IP로 고정할 수 있다.

  # LB IP는 서비스의 외부 엔드포인트(External IP)로 사용된다.
  # 매니지드 서비스라면, LB IP가 공인IP일 것이고, 클라이언트가 직접사용하는 주소가 된다.
  # NAT 등 사설망으로 구성된 환경이라면, LB IP가 사설 IP일 것이고, 클라이언트가 접속시 직접사용하는 IP는 아니다.
  #####################################################
  #loadBalancerIP: 172.19.1.3


  #####################################################
  # externalIPs:
  # 원래, LB타입 서비스의 External IP(외부노출 IP)는 LoadBalancer의 IP를 그대로 이용하는데,
  # 이 옵션을 쓰면,  추가적인 External IP를 지정할 수 있다.
  
  # LoadBalancer가 없을 때 간단한 테스트를 하거나, 소규모 배포시 주로 사용하는 옵션
  #####################################################
  #externalIPs:
  #  - 172.19.1.2  
  #  - 172.19.1.3



  
  selector:
    app: sampleapp
    tier: db
