
# 1. MetalLB 공홈에서 메니페스트 링크 확인 후 적용(metallb-system namespace 생성)
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml

# 2. 아래 메니페스트로 로드밸런서가 할당할 IP범위 설정
# 이미 생성된 metallb-system을 수정하는 것이다.
# kubectl apply -f metallb-for-k3s.yml

# 3. LB타입 Service 실행
# External IP가 의도대로 할당된 것을 확인할 수 있다.
# 다만 왜인지 telnet 연결은 잘 되지 않는다. 보안망이라 그런가?
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nat
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.2-10.0.0.5
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system