
# 1. MetalLB 공홈에서 메니페스트 링크 확인 후 적용(metallb-system namespace 생성)
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml

# 2. 아래 메니페스트로 로드밸런서가 할당할 IP범위 설정
# 이미 생성된 metallb-system을 수정하는 것이다.
# kubectl apply -f metallb-for-k3s.yml

# 3. LB타입 Service 실행

# 4. IP 할당 확인
# 
# kubectl get svc
# kubectl describe svc {서비스명}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nat
  namespace: metallb-system
spec:
  addresses:
    - 172.19.0.1-172.19.15.255
    # 현재 네트워크 대역과 맞춰준다.
    # 로컬 1노드 환경에서 테스트하는것이라면 결국 NodeIP를 쓰게된다.
    # 다른 걸로 강제할당하면 External IP 등으로 등록은 되지만, 실제 네트워크 설정이 되어있지 않으므로 접속안된다.
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system