apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app.kubernetes.io/name: metallb
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  # addresses자리는 로드밸런서가 할당할 <START_IP>-<END_IP> 범위를 의미
  # 클라우드기반이 아니므로, 실제 존재하는 Node들의 IP 범위를 기술
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - <START_IP>-<END_IP>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: metallb-system
  name: controller
spec:
  selector:
    matchLabels:
      app: controller
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: metallb/controller:v0.10.0
        ports:
        - name: api
          containerPort: 7472
          protocol: TCP
        - name: controller
          containerPort: 7471
          protocol: TCP
        args:
        - --port=7472
        - --config= /config/config
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: config
          items:
          - key: config
            path: config
---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: controller
  labels:
    app: controller
spec:
  type: ClusterIP
  selector:
    app: controller
  ports:
  - name: api
    port: 7472
    protocol: TCP
  - name: controller
    port: 7471
    protocol: TCP
