# Deployment
# ReplicaSet과 설정은 거의 동일하다. Deployment는 업데이트할 때 진가를 발휘한다.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy-st
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo
      tier: app
  minReadySeconds: 5
  # 배포 전략 설정
  strategy:
    type: RollingUpdate  # RollingUpdate, Recreate, Canary 중 선택
    rollingUpdate:
      maxSurge: 3        # 
      maxUnavailable: 3  # 
  
  template:
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: ghcr.io/subicura/echo:v2
          livenessProbe:
            httpGet:
              path: /
              port: 3000