# Deployment
# ReplicaSet과 설정은 거의 동일하다. Deployment는 업데이트할 때 진가를 발휘한다.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-echo
spec:
  replicas: 4
  selector:    # selector: label기반으로 다른 오브젝트를 식별하고 제어한다.
    matchLabels: # 체크할 Label. 하위 key-value가 모두 같아야 한다. 
      app: pod-echo
      tier: app
  template:
    metadata:
      labels:
        app: pod-echo
        tier: app
    spec:
      containers:
        - name: con-echo
          image: ghcr.io/subicura/echo:v1